// Generated by Supabase from the live schema. Regenerate after migrations:
//   pnpm exec supabase gen types typescript --project-id fjwgophensdgchvvpxnh
// or via the Supabase MCP `generate_typescript_types`. Do NOT hand-edit.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      account: {
        Row: {
          accessToken: string | null
          accessTokenExpiresAt: string | null
          accountId: string
          createdAt: string
          id: string
          idToken: string | null
          password: string | null
          providerId: string
          refreshToken: string | null
          refreshTokenExpiresAt: string | null
          scope: string | null
          updatedAt: string
          userId: string
        }
        Insert: {
          accessToken?: string | null
          accessTokenExpiresAt?: string | null
          accountId: string
          createdAt?: string
          id: string
          idToken?: string | null
          password?: string | null
          providerId: string
          refreshToken?: string | null
          refreshTokenExpiresAt?: string | null
          scope?: string | null
          updatedAt?: string
          userId: string
        }
        Update: {
          accessToken?: string | null
          accessTokenExpiresAt?: string | null
          accountId?: string
          createdAt?: string
          id?: string
          idToken?: string | null
          password?: string | null
          providerId?: string
          refreshToken?: string | null
          refreshTokenExpiresAt?: string | null
          scope?: string | null
          updatedAt?: string
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "account_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_predictions: {
        Row: {
          cost_usd: number | null
          created_at: string
          feedback: string | null
          id: string
          latency_ms: number | null
          model_used: string
          predicted_complexity: number
          predicted_price_high: number
          predicted_price_low: number
          prompt_input_hash: string
          quote_id: string | null
          rationale: string
        }
        Insert: {
          cost_usd?: number | null
          created_at?: string
          feedback?: string | null
          id?: string
          latency_ms?: number | null
          model_used: string
          predicted_complexity: number
          predicted_price_high: number
          predicted_price_low: number
          prompt_input_hash: string
          quote_id?: string | null
          rationale: string
        }
        Update: {
          cost_usd?: number | null
          created_at?: string
          feedback?: string | null
          id?: string
          latency_ms?: number | null
          model_used?: string
          predicted_complexity?: number
          predicted_price_high?: number
          predicted_price_low?: number
          prompt_input_hash?: string
          quote_id?: string | null
          rationale?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_predictions_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      cad_uploads: {
        Row: {
          created_at: string
          estimator_id: string
          file_size_bytes: number
          height_inches: number | null
          id: string
          mime_type: string
          original_filename: string
          parse_error: string | null
          path_count: number | null
          storage_path: string
          width_inches: number | null
        }
        Insert: {
          created_at?: string
          estimator_id: string
          file_size_bytes: number
          height_inches?: number | null
          id?: string
          mime_type: string
          original_filename: string
          parse_error?: string | null
          path_count?: number | null
          storage_path: string
          width_inches?: number | null
        }
        Update: {
          created_at?: string
          estimator_id?: string
          file_size_bytes?: number
          height_inches?: number | null
          id?: string
          mime_type?: string
          original_filename?: string
          parse_error?: string | null
          path_count?: number | null
          storage_path?: string
          width_inches?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "cad_uploads_estimator_id_fkey"
            columns: ["estimator_id"]
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          company: string | null
          created_at: string
          email: string | null
          estimator_id: string
          id: string
          is_demo_sample: boolean
          name: string
          notes: string | null
          phone: string | null
          updated_at: string
        }
        Insert: {
          company?: string | null
          created_at?: string
          email?: string | null
          estimator_id: string
          id?: string
          is_demo_sample?: boolean
          name: string
          notes?: string | null
          phone?: string | null
          updated_at?: string
        }
        Update: {
          company?: string | null
          created_at?: string
          email?: string | null
          estimator_id?: string
          id?: string
          is_demo_sample?: boolean
          name?: string
          notes?: string | null
          phone?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "customers_estimator_id_fkey"
            columns: ["estimator_id"]
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: ["id"]
          },
        ]
      }
      industries: {
        Row: {
          certification_premium: number
          created_at: string
          description: string | null
          id: string
          name: string
          required_certifications: string[]
        }
        Insert: {
          certification_premium?: number
          created_at?: string
          description?: string | null
          id?: string
          name: string
          required_certifications?: string[]
        }
        Update: {
          certification_premium?: number
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          required_certifications?: string[]
        }
        Relationships: []
      }
      materials: {
        Row: {
          active: boolean
          cost_per_sq_in: number
          created_at: string
          description: string | null
          durability_score: number
          id: string
          name: string
          type: string
        }
        Insert: {
          active?: boolean
          cost_per_sq_in: number
          created_at?: string
          description?: string | null
          durability_score: number
          id?: string
          name: string
          type: string
        }
        Update: {
          active?: boolean
          cost_per_sq_in?: number
          created_at?: string
          description?: string | null
          durability_score?: number
          id?: string
          name?: string
          type?: string
        }
        Relationships: []
      }
      products: {
        Row: {
          active: boolean
          base_price_per_sq_in: number
          category: string
          created_at: string
          description: string | null
          id: string
          min_qty: number
          name: string
          setup_fee: number
        }
        Insert: {
          active?: boolean
          base_price_per_sq_in: number
          category: string
          created_at?: string
          description?: string | null
          id?: string
          min_qty?: number
          name: string
          setup_fee?: number
        }
        Update: {
          active?: boolean
          base_price_per_sq_in?: number
          category?: string
          created_at?: string
          description?: string | null
          id?: string
          min_qty?: number
          name?: string
          setup_fee?: number
        }
        Relationships: []
      }
      quote_lines: {
        Row: {
          cad_upload_id: string | null
          created_at: string
          height_inches: number
          id: string
          line_estimate: number
          material_id: string
          position: number
          product_id: string
          quantity: number
          quote_id: string
          width_inches: number
        }
        Insert: {
          cad_upload_id?: string | null
          created_at?: string
          height_inches: number
          id?: string
          line_estimate: number
          material_id: string
          position?: number
          product_id: string
          quantity: number
          quote_id: string
          width_inches: number
        }
        Update: {
          cad_upload_id?: string | null
          created_at?: string
          height_inches?: number
          id?: string
          line_estimate?: number
          material_id?: string
          position?: number
          product_id?: string
          quantity?: number
          quote_id?: string
          width_inches?: number
        }
        Relationships: [
          {
            foreignKeyName: "quote_lines_cad_upload_id_fkey"
            columns: ["cad_upload_id"]
            isOneToOne: false
            referencedRelation: "cad_uploads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quote_lines_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "materials"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quote_lines_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quote_lines_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      quotes: {
        Row: {
          ai_complexity_score: number | null
          ai_rationale: string | null
          ai_suggested_price_high: number | null
          ai_suggested_price_low: number | null
          base_estimate: number
          certifications: string[]
          created_at: string
          customer_email: string | null
          customer_id: string | null
          customer_name: string
          estimator_id: string
          final_price: number | null
          height_inches: number
          id: string
          industry_id: string
          is_demo_sample: boolean
          material_id: string
          notes: string | null
          product_id: string
          quantity: number
          status: string
          updated_at: string
          width_inches: number
        }
        Insert: {
          ai_complexity_score?: number | null
          ai_rationale?: string | null
          ai_suggested_price_high?: number | null
          ai_suggested_price_low?: number | null
          base_estimate: number
          certifications?: string[]
          created_at?: string
          customer_email?: string | null
          customer_id?: string | null
          customer_name: string
          estimator_id: string
          final_price?: number | null
          height_inches: number
          id?: string
          industry_id: string
          is_demo_sample?: boolean
          material_id: string
          notes?: string | null
          product_id: string
          quantity: number
          status?: string
          updated_at?: string
          width_inches: number
        }
        Update: {
          ai_complexity_score?: number | null
          ai_rationale?: string | null
          ai_suggested_price_high?: number | null
          ai_suggested_price_low?: number | null
          base_estimate?: number
          certifications?: string[]
          created_at?: string
          customer_email?: string | null
          customer_id?: string | null
          customer_name?: string
          estimator_id?: string
          final_price?: number | null
          height_inches?: number
          id?: string
          industry_id?: string
          is_demo_sample?: boolean
          material_id?: string
          notes?: string | null
          product_id?: string
          quantity?: number
          status?: string
          updated_at?: string
          width_inches?: number
        }
        Relationships: [
          {
            foreignKeyName: "quotes_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_estimator_id_fkey"
            columns: ["estimator_id"]
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_industry_id_fkey"
            columns: ["industry_id"]
            isOneToOne: false
            referencedRelation: "industries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "materials"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      session: {
        Row: {
          createdAt: string
          expiresAt: string
          id: string
          ipAddress: string | null
          token: string
          updatedAt: string
          userAgent: string | null
          userId: string
        }
        Insert: {
          createdAt?: string
          expiresAt: string
          id: string
          ipAddress?: string | null
          token: string
          updatedAt?: string
          userAgent?: string | null
          userId: string
        }
        Update: {
          createdAt?: string
          expiresAt?: string
          id?: string
          ipAddress?: string | null
          token?: string
          updatedAt?: string
          userAgent?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "session_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: ["id"]
          },
        ]
      }
      user: {
        Row: {
          createdAt: string
          email: string
          emailVerified: boolean
          id: string
          image: string | null
          name: string
          updatedAt: string
        }
        Insert: {
          createdAt?: string
          email: string
          emailVerified?: boolean
          id: string
          image?: string | null
          name: string
          updatedAt?: string
        }
        Update: {
          createdAt?: string
          email?: string
          emailVerified?: boolean
          id?: string
          image?: string | null
          name?: string
          updatedAt?: string
        }
        Relationships: []
      }
      verification: {
        Row: {
          createdAt: string | null
          expiresAt: string
          id: string
          identifier: string
          updatedAt: string | null
          value: string
        }
        Insert: {
          createdAt?: string | null
          expiresAt: string
          id: string
          identifier: string
          updatedAt?: string | null
          value: string
        }
        Update: {
          createdAt?: string | null
          expiresAt?: string
          id?: string
          identifier?: string
          updatedAt?: string | null
          value?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
